### ISSUE TITLE
Include DB Query in Trace Without Logging

### ISSUE THREAD

**Issue by s1rc** [ipunkt/laravel-jaeger#2]
Is it possible to include the DB query in the trace without adding to `Log::debug()`?

**Comment by svensp** [comment]
You can send any data you want with the following code:
```php
app('current-context')->log($someDataArray);
```

So you can disable sending queries to the debug log in the config `jaeger.log.database=false`, then add your own DB listener to send the query to jaeger.
```php
\DB::listen(function($query) {
  app('current-context')->log([
                'query' => str_replace('"', "'", $query->sql),
                'bindings' => $query->bindings,
                'time' => $query->time . 'ms',
            ]);
});
```

**Comment by s1rc** [comment]
Thank you that worked when adding it to my `AppServiceProvider` and including your Middleware.
